apiVersion: v1
kind: PersistentVolume
metadata:
  name: ts3server-pv
  namespace: ts3server
  labels:
    app: ts3server
spec:
  capacity:
    storage: 200Mi
  hostPath:
    path: /var/ts3server/teamspeak/
    type: ''
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: ts3server
    name: ts3server-pvc
    apiVersion: v1
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem