# ---------------------------
# Gluetun Deployment
# ---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: stremio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      containers:
        - name: gluetun
          image: qmcgaw/gluetun
          securityContext:
            privileged: true
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "privado"
            - name: SERVER_COUNTRIES
              value: "Netherlands"
            - name: OPENVPN_USER
              value: "pvstbpqv592410"
            - name: OPENVPN_PASSWORD
              value: "" #PASSWORD PRIVADO VPN
            - name: HTTPPROXY
              value: "on"
            - name: HTTPPROXY_LISTENING_ADDRESS
              value: ":8080"
            - name: FIREWALL_INPUT_PORTS
              value: "8080"
          ports:
            - containerPort: 8080
          livenessProbe:
            exec:
              command: ["/gluetun-entrypoint", "healthcheck"]
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: gluetun
  namespace: stremio
spec:
  selector:
    app: gluetun
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

