apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mediaflow-proxy
  name: mediaflow-proxy
  namespace: stremio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediaflow-proxy
  template:
    metadata:
      labels:
        app: mediaflow-proxy
    spec:
      containers:
      - name: mediaflow-proxy
        image: mhdzumair/mediaflow-proxy
        imagePullPolicy: Always
        env:
        - name: API_PASSWORD
          value: "" # Set this to your API password
        - name: PROXY_URL
          value: http://127.0.0.1:7777 #http://warp-cloudflare-vpn:1080
        - name: TRANSPORT_ROUTES
          value: '{ "https://torrentio.strem.fun": { "proxy": true }, "https://api.real-debrid.com": { "proxy": true }}'
        ports:
        - containerPort: 8888
          protocol: TCP
      - name: gluetun-vpn
        image: qmcgaw/gluetun
        imagePullPolicy: Always
        env:
        - name: VPN_SERVICE_PROVIDER
          value: protonvpn
        - name: SERVER_COUNTRIES
          value: Netherlands
        - name: HTTPPROXY
          value: "on"
        - name: HTTPPROXY_LISTENING_ADDRESS
          value: ":7777"
        - name: HTTPPROXY_STEALTH
          value: "on"
        - name: OPENVPN_USER
          value: 2mlfOwBB4XCxuZzQ
        - name: OPENVPN_PASSWORD
          value: ""
        ports:
        - containerPort: 7777
        - containerPort: 8000
        - containerPort: 53
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
      dnsPolicy: ClusterFirst
      restartPolicy: Always
